# # .github/workflows/sync.yml
# name: Sync Fork

# on:
#   push: # push 时触发, 主要是为了测试配置有没有问题
#   schedule:
#     - cron: '0 */8 * * *' # 每8小时一次同步
# jobs:
#   repo-sync:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: TG908/fork-sync@v1.1
#         with:
#           github_token: ${{ secrets.GITHUB_TOKEN }} # 这个 token action 会默认配置, 这里只需这样写就行
#           owner: owid # fork 上游项目 owner
#           head: master # fork 上游项目需要同步的分支
#           base: master # 需要同步到本项目的目标分支
# #   sync:
# #     needs: repo-sync
# #     runs-on: ubuntu-latest
# #     steps:
# #     - name: Sync to Gitee
# #       uses: wearerequired/git-mirror-action@master
# #       env:
# #         SSH_PRIVATE_KEY: ${{ secrets.GITEE_RSA_PRIVATE_KEY }}
# #       with:
# #         # 来源仓库
# #         source-repo: "git@github.com:LesterHoly/covid-19-data.git"
# #         # 目标仓库
# #         destination-repo: "git@gitee.com:shadow_walker/covid-19-data.git"
